### ISSUE TITLE
Calling getScripCodes() throws FileNotFoundError

### ISSUE THREAD

**Issue by samRddhimat** [sdabhi23/bsedata#11]
from bsedata.bse import BSE
b = BSE()
b.getScripCodes()

the above snippet throws FileNotFoundError as below.

C:\ProgramData\Anaconda3\lib\site-packages\bsedata\bse.py in getScripCodes(self)
     89         :return: a dictionary with scrip codes as keys and company names as values
     90         """
---> 91         f = open('stk.json', 'r')
     92         return json.loads(f.read())
     93 

FileNotFoundError: [Errno 2] No such file or directory: 'stk.json'

**Comment by sdabhi23** [comment]
Hey @samRddhimat please check #7 for some context and solution. Also if you would like to see some different behaviour for the function, your suggestions are very much welcome!

**Comment by sdabhi23** [comment]
closing as inactive
