### ISSUE TITLE
Problem Fetching some Indices 

### ISSUE THREAD

**Issue by darkHorseStocks** [sdabhi23/bsedata#12]
from bsedata.bse import BSE
b = BSE()
print(b)
indices = b.getIndices(category='market_cap/broad')
print(indices)

**OUTPUT-:**
Driver Class for Bombay Stock Exchange (BSE)
{'indices': []}

i am not able to get any data for this category as well as for some others too.

Also i would request to let me know if there is any way where i could fetch historical data of the indices as well as for the stocks which are not listed on nse.

**Comment by vanigupta20024** [comment]
Having the same problem, getIndices() isn't working.

**Comment by sdabhi23** [comment]
Can you please share the stack trace if it's throwing an error?

**Comment by vanigupta20024** [comment]
No, it's not throwing an error, rather, it returns a dict object with empty indices list.
![image](https://user-images.githubusercontent.com/53790649/118374524-387ac500-b5da-11eb-8714-1bd64f7e3d97.png)

Please refer the attached image.

**Comment by srinivasakumar-a** [comment]
Getting same issue, Indices List is Empty!!

```
from bsedata.bse import BSE
b = BSE()
print(b)
indices = b.getIndices(category='market_cap/broad')
print(indices)
```

OUTPUT-:
`{'indices': []}`
