### ISSUE TITLE
Create custom exception

### ISSUE THREAD

**Issue by ashishdasari148** [sdabhi23/bsedata#18]
when using the method getQuote with scripCodes like '538936', an error AttributeError: 'NoneType' object has no attribute 'split' is being thrown
![Screenshot (1)](https://user-images.githubusercontent.com/59196150/85275377-e0a50e00-b49d-11ea-9720-ba5bc39ffbbd.png)

**Comment by sdabhi23** [comment]
The company / scrip code has been suspended and hence the data is not available. The library only works for valid scrip codes. Please refresh the following screenshot:

![Screenshot_20200622-155057~2](https://user-images.githubusercontent.com/25759344/85277046-6033dc80-b4a0-11ea-8625-e546d575c734.png)
