### ISSUE TITLE
Additions of Financial Data (Results & Annual Reports)

### ISSUE THREAD

**Issue by sbipl** [sdabhi23/bsedata#28]
**Financial Tab -> Annual Reports :**
https://www.bseindia.com/stock-share-price/tata-motors-ltd/tatamotors/500570/financials-annual-reports/

**Financial Tab -> Results :**
https://www.bseindia.com/stock-share-price/tata-motors-ltd/tatamotors/500570/financials-results/
**Prior Period:** 
https://www.bseindia.com/corporates/Comp_Results.aspx?Code=500570

**Comment by KeshavAnandBhagat** [comment]
can you please assign me this issue

**Comment by sdabhi23** [comment]
This feature is outside the scope of this library
