### ISSUE TITLE
getScriptCode function is not working

### ISSUE THREAD

**Issue by vinaysuneja90** [sdabhi23/bsedata#32]
![image](https://user-images.githubusercontent.com/16670320/154823063-73f05b40-a32d-40b0-b5fe-40644f83dc6d.png)
![image](https://user-images.githubusercontent.com/16670320/154823083-86eff02b-4091-4ac0-9c58-cb8fae8198a8.png)

**Comment by sdabhi23** [comment]
Hi @vinaysuneja90 thank you for reporting this issue. I have fixed this issue. will release a new version pypi in a couple of days

**Comment by toraghulravi** [comment]
@sdabhi23 Any update on the new version?

**Comment by sdabhi23** [comment]
@vinaysuneja90 @toraghulravi a new version has been published on PyPI with the fix. Please update to the new version. Feel free to reopen the issue if the problem persists
