### ISSUE TITLE
Do update scrip code methods need to have access to local file system?

### ISSUE THREAD

**Issue by kanavbatra** [sdabhi23/bsedata#38]
It seems the update script code methods needs access to the local file system, ' BSE(update_codes=True)` and `bse_object.updateScripCodes()`. 

I get an OS error when deploying an app on AWS, `Read-only file system: 'stk.json'`

Do these methods need access to local file systems? Is there a workaround for this?

**Comment by sdabhi23** [comment]
@kanavbatra yes, these methods store the scripcode data on the file. There is not workaround for it if you want access to this data, we need to store it somewhere.

Can you share more details about the way you are trying to deploy it? Maybe I can help you figure out a better way to deploy
