### ISSUE TITLE
Historical Deliverable quantity data of each stock.

### ISSUE THREAD

**Issue by aayushhn123** [sdabhi23/bsedata#39]
I am not able to extract the "deliverable volume" or "deliverable quantity" of any stock . Could you help me with this.

**Comment by sdabhi23** [comment]
hey, you need to share more details about this. Sharing where this data is shown on the BSE website is a good place to start

**Comment by aayushhn123** [comment]
sure.
I am not able to find the BSE link now but here is the NSE link
https://www.nseindia.com/report-detail/eq_security

**Comment by aayushhn123** [comment]
here you go the BSE link:
https://www.bseindia.com/markets/equity/EQReports/GrossShortPos.aspx?flag=0

**Comment by sdabhi23** [comment]
are you able to find it on this website: https://m.bseindia.com/?

**Comment by sdabhi23** [comment]
Closing this issue as it is stale and the requested information was not provided. Please raise a new issue if this is still needed.
