### ISSUE TITLE
Missing Price Band attribute

### ISSUE THREAD

**Issue by sdabhi23** [sdabhi23/bsedata#5]
I have observed a very weird behavior  in few responses where the price band attribute is not found on the page.

Reproduced randomly and accidentally in browser as well (on https://m.bseindia.com)

**Cause:** Unknown

**Work around:** Opened a stock page from https://bseinda.com which was also missing Price Band and force refresh it (shortcut key for Firefox: Ctrl + F5, for Chrome: Shift + F5).

**Comment by shikharparikh** [comment]
The PriceBand error still exists for a variety of stocks. I tried pinging the website every 1 minute, but after 4-6 iterations, PriceBand error shows up. Please advise @sdabhi23

**Comment by sdabhi23** [comment]
@shikharparikh I am still looking for the root cause. Currently, I have implemented a temporary workaround which will prevent the code from throwing an error. Can you please elaborate on the kind of behaviour you are expecting?

**Comment by shikharparikh** [comment]
So basically, I am using the getQuote function every minute to get the currentValue, pChange and Change for a list of 18 stocks in my portfolio. I have managed to concurrently grab the above mentioned parameters for these 18 stocks. However, somewhere between the 4th and 6th iteration, the PriceBand error is thrown. 
Suggestion: can you include a try: except mechanism that returns an NA value if the priceBand / any other parameter is unavailable if continuously pinged.

**Comment by sdabhi23** [comment]
Can you please share the version of bsedata that you are using? I have already done the try/catch implementation as a temporary fix

**Comment by shikharparikh** [comment]
I am currently on 0.3.1

**Comment by sdabhi23** [comment]
Can you please share the stack trace of the error?

**Comment by shikharparikh** [comment]
> /usr/local/lib/python3.6/dist-packages/bsedata/bse.py in getQuote(self, scripCode)
     58         :return: a dictionary which contain details about the stock
     59         """
---> 60         return quote.quote(scripCode)
     61 
     62     def getIndices(self, category):

>/usr/local/lib/python3.6/dist-packages/bsedata/quote.py in quote(scripCode)
     94             continue
     95 
---> 96     if res['priceBand'] != '':
     97         for tbody in soup('tbody'):
     98             try:

>KeyError: 'priceBand'

**Comment by sdabhi23** [comment]
@shikharparikh seems like BSE has made some changes to the site. This error is caused due to another missing attribute and completely unrelated to this bug. I'll look into this and release a new version at the earliest. Until then can you try using try and except blocks in your driver code as a work around?
