### ISSUE TITLE
getScripCodes() returns error if updateScripCodes() is not executed before.

### ISSUE THREAD

**Issue by HasanFaraaz** [sdabhi23/bsedata#7]
Executing getScripCodes returns in stk.json file not found error.  To overcome this updateScripCodes() needs to be executed first as this makes the file stk.json.

**Comment by sdabhi23** [comment]
Hey @HasanFaraaz please go through the docs properly: https://bsedata.readthedocs.io/en/latest/usage.html#instantiation

**Comment by sdabhi23** [comment]
closing as inactive
