### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by amitkadivar1** [sdabhi23/bsedata#9]
when I try to get detail of this code '538651' then give me Error like this 

`res['change'] = span.string.split('(')[0].strip()`

this Exception generates due to not found **change**, **industry** or **any** other fields.
so please fix this issue

**Comment by YOGESHAAR** [comment]
Hi Amitkadivar1,

I faced the same issue (AttributeError: 'NoneType' object has no attribute 'split'), I updated all such instances in the quote.py and it is working fine. I can share it, pz let me know

**Comment by sdabhi23** [comment]
Hey @YOGESHAAR, can you please send a PR to fix this? I have been working on this a long time, but couldn't figure out why the bug occurs in the very first place, even though I have been able to reproduce it a lot of times.

**Comment by sweetatyagiaz** [comment]
> Hi Amitkadivar1,
> 
> I faced the same issue (AttributeError: 'NoneType' object has no attribute 'split'), I updated all such instances in the quote.py and it is working fine. I can share it, pz let me know

I am facing the same problem. Can you share the solution. Thanks
